[package]
name = "resource_rush"
version = "0.1.0"
cairo-version = "2.2.0"

[cairo]
sierra-replace-ids = true

[dependencies]
# Dojo dependency from GitHub. Adjust tag/version as needed.
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.2.2" }

[[target.dojo]]
[tool.dojo]
initializer_class_hash = "0xbeef"  # Placeholder; override at deploy time.

[tool.dojo.env]
# Local RPC for development. Change this to your Katana node.
rpc_url = "http://localhost:5050/"

# Default development account (seed 0) provided by Katana. Replace with
# appropriate addresses/keys when deploying on testnet/mainnet.
account_address = "0x517ececd29116499f4a1b64b094da79ba08dfd54a3edaa316134c41f8160973"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"
